apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: backend-tests-go-yquzkavq
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/backend-tests-go-yquzkavq:de8ffd8bc28df819d71310b77e7294cf3b629ea8@sha256:cad66d894b2b6e09f8c4ec338cfe7825d304fd2d15e6cb06a284dbfc9c765f8b
        name: container-image  
