apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: backend-tests-go-yquzkavq
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/backend-tests-go-yquzkavq:5fd61baf72d21aa382186e2f7caff9f21f550e62@sha256:0d1eba188ae6646e49d714bf790bbc929ed5d959eb8b9147a7bd9d54a3c3a9f9
          name: container-image
